#!/bin/sh
### BEGIN INIT INFO
# Provides:          populate_var
# Required-Start:    $local_fs 
# Required-Stop:     
# Default-Start:     S
# Default-Stop:      
# X-Start-Before:    bootmisc portmap
# Short-Description: Create necessary files in /var
# Description:       Creates /var/run and other files/directories needed at boot
### END INIT INFO

# Author: Daniel Barlow <dan@stargreen.com>

do_start () {
	for i in \
	    cache \
	    lib \
	    lib/dbus \
	    lib/dhcp \
	    lib/nfs \
	    lib/varnish/clone \
	    lib/varnish/etc \
	    lock \
	    log \
	    log/fsck \
	    log/sysstat \
	    monit \
	    run \
	    run/rticulate \
	    spool \
	    tmp \
	    ;do
	  mkdir -p /var/$i ;
	done
	chown varnish /var/lib/varnish/etc
	chown stargreen /var/run/rticulate
}

case "$1" in
  start|"")
	do_start
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	# No-op
	;;
  *)
	echo "Usage: populate_var [start|stop]" >&2
	exit 3
	;;
esac

:
